name: Continous Integration (CI)

on:
  push:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a single script to show the possible success of its functionality
        run: echo Hello World!  It is most likely functioning correctly.
        
